### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by kotowick** [muchrm/docker-wine-mt4#1]
1. What is the password when connecting via VNC
EDIT:  add to Dockerfile
```
ARG VNC_PASSWORD=secret

ENV VNC_PASSWORD ${VNC_PASSWORD}
```

Change:
```
x11vnc -display :1 -xkb -forever
```
to
```
x11vnc -display :1 -xkb -forever -passwd $VNC_PASSWORD
```

2. Does mt4 auto start? (I didn't see anything related to starting it in the Dockerfile, and didn't see it running in the process list)

**Comment by muchrm** [comment]
@kotowick 
1. can you sent a pull request to me ?
2. yes it's doest not auto startMT4 because i will setup a EA and server ip later

**Comment by muchrm** [comment]
#2
